apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.grafana.deploymentName }}
  name: {{ .Values.grafana.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    nodePort: {{ .Values.grafana.nodePort }}
  selector:
    app: {{ .Values.grafana.deploymentName }}
  type: NodePort