apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.configMapName }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.grafana.configMapName }}
data:
  defaultDatasources.yaml: |-
    apiVersion: 1

    datasources:
    - name: TimescaleDB
      type: postgres
      user: postgres
      database: postgres
      url: $TIMESCALEDB_HOST:5432
      basicAuth: false
      jsonData:
        sslmode: disable
        tlsAuth: false
        tlsSkipVerify: true
        timescaledb: true
        postgresVersion: 1200
      secureJsonData:
        password: $TIMESCALEDB_PASSWORD
  defaultDashboards.yaml: |-
    apiVersion: 1

    providers:
      - name: 'GJD: Provided dashboard'
        type: file
        disableDeletion: true
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
  basicDashboard.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 2,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": "TimescaleDB",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single"
            }
          },
          "targets": [
            {
              "format": "time_series",
              "group": [],
              "metricColumn": "none",
              "rawQuery": false,
              "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM system_cpu\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1",
              "refId": "A",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "column"
                  }
                ]
              ],
              "table": "system_cpu",
              "timeColumn": "\"time\"",
              "timeColumnType": "timestamptz",
              "where": [
                {
                  "name": "$__timeFilter",
                  "params": [],
                  "type": "macro"
                }
              ]
            }
          ],
          "title": "Panel Title",
          "type": "timeseries"
        }
      ],
      "schemaVersion": 32,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Basic",
      "uid": "g9Xufec7k",
      "version": 1
    }