apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-external-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30030
  selector:
    app: grafana
  type: NodePort