apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.grafana.deploymentName }}
  name: {{ .Values.grafana.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.grafana.useLoadBalancer }}
  type: LoadBalancer
  {{- else }}
  type: NodePort
  {{- end }}
  selector:
    app: {{ .Values.grafana.deploymentName }}
  ports:
  - port: 3000
    protocol: TCP
    {{- if .Values.grafana.useLoadBalancer }}
    targetPort: 3000
    {{- else }}
    nodePort: {{ .Values.grafana.nodePort }}
    {{- end }}