apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.grafana.deploymentName }}
  name: {{ .Values.grafana.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.grafana.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.grafana.deploymentName }}
    spec:
      containers:
      - image: grafana/grafana
        name: {{ .Values.grafana.deploymentName }}
        ports:
          - containerPort: 3000