# Default values for telemetry-demo
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: telemetry-streaming-quickstart

# Grafana default values
grafana:
  deploymentName: grafana
  serviceName: grafana-external-svc
  nodePort: 30030

# OpenTelemetry default values
openTelemetry:
  deploymentName: otel-collector
  configMapName: otel-collector-conf
  serviceName: otel-collector-prom-svc
  externalServiceName: otel-collector-ingest-svc
  nodePort: 30681

# Prometheus default values
prometheus:
  deploymentName: prometheus
  configMapName: prometheus-conf
  serviceName: prometheus-svc

# Promscale default values
promscale:
  deploymentName: promscale
  serviceName: promscale-svc
  secretName: promscale-connection-string

# Telemetry-Model default values
telemetryModel:
  cronJobName: telemetry-model-builder
  configMapName: telemetry-model-builder-conf
  secretName: telemetry-model-db

# TimescaleDB default values
timescaledb:
  deploymentName: timescaledb
  serviceName:  timescaledb-svc
  secretName: timescaledb-password
  username: postgres
  password: