# Default values for telemetry-demo
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: telemetry-streaming-quickstart

timescaledb:
  password: 
  username: postgres