apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    app: prometheus
  type: ClusterIP