apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.prometheus.deploymentName }}
  name: {{ .Values.prometheus.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    app: {{ .Values.prometheus.deploymentName }}
  type: ClusterIP