apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.prometheus.deploymentName }}
  name: {{ .Values.prometheus.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prometheus.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.deploymentName }}
    spec:
      containers:
      - image: prom/prometheus
        name: {{ .Values.prometheus.deploymentName }}
        volumeMounts:
        - name: {{ .Values.prometheus.configMapName }}
          mountPath: /etc/prometheus
        ports:
          - containerPort: 9090
      volumes:
      - name: {{ .Values.prometheus.configMapName }}
        configMap:
          name: {{ .Values.prometheus.configMapName }}
          items:
          - key: prometheus.yml
            path: prometheus.yml