apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.openTelemetry.configMapName }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.openTelemetry.configMapName }}
data:
  otelconfig.yaml: |-
    receivers:
      otlp:
        protocols:
          http:

    processors:
      batch:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9088"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]