apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.openTelemetry.deploymentName }}
  name: {{ .Values.openTelemetry.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9088
    protocol: TCP
  selector:
    app: {{ .Values.openTelemetry.deploymentName }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.openTelemetry.deploymentName }}
  name: {{ .Values.openTelemetry.externalServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.openTelemetry.useLoadBalancer }}
  type: LoadBalancer
  {{- else }}
  type: NodePort
  {{- end }}
  selector:
    app: {{ .Values.openTelemetry.deploymentName }}
  ports:
  - port: 55681
    protocol: TCP
    {{- if .Values.openTelemetry.useLoadBalancer }}
    targetPort: 55681
    {{- else }}
    nodePort: {{ .Values.openTelemetry.nodePort }}
    {{- end }}