apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.openTelemetry.deploymentName }}
  name: otel-collector
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.openTelemetry.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.openTelemetry.deploymentName }}
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib
        name: {{ .Values.openTelemetry.deploymentName }}
        volumeMounts:
        - name: {{ .Values.openTelemetry.configMapName }}
          mountPath: /etc/otel
        ports:
          - containerPort: 55681
          - containerPort: 9088
      volumes:
      - name: {{ .Values.openTelemetry.configMapName }}
        configMap:
          name: {{ .Values.openTelemetry.configMapName }}
          items:
          - key: otelconfig.yaml
            path: config.yaml