apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-collector
  name: otel-collector-prom-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9088
    protocol: TCP
  selector:
    app: otel-collector
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-collector
  name: otel-collector-ingest-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 55681
    protocol: TCP
    nodePort: 30681
  selector:
    app: otel-collector
  type: NodePort