apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.openTelemetry.deploymentName }}
  name: {{ .Values.openTelemetry.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9088
    protocol: TCP
  selector:
    app: {{ .Values.openTelemetry.deploymentName }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.openTelemetry.deploymentName }}
  name: {{ .Values.openTelemetry.externalServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 55681
    protocol: TCP
    nodePort: {{ .Values.openTelemetry.nodePort }}
  selector:
    app: {{ .Values.openTelemetry.deploymentName }}
  type: NodePort