apiVersion: v1
data:
  password:  {{ .Values.timescaledb.password | b64enc }}
  username: {{ .Values.timescaledb.username | b64enc }}
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: telemetry-model-db