apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.telemetryModel.cronJobName }}
  namespace: {{ .Values.namespace }}
spec:
  jobTemplate:
    metadata:
      name: {{ .Values.telemetryModel.cronJobName }}
    spec:
      template:
        metadata:
        spec:
          containers:
          - image: {{ .Values.telemetryModel.imageName }}
            name: {{ .Values.telemetryModel.cronJobName }}
            env:
            - name: TS_HOST
              value: "timescaledb-svc"
            - name: TS_USER
              valueFrom:
                secretKeyRef:
                  name: telemetry-model-db
                  key: username
            - name: TS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telemetry-model-db
                  key: password
            volumeMounts:
            - name: {{ .Values.telemetryModel.configMapName }}
              mountPath: /etc/telemetry-models
          volumes:
          - name: {{ .Values.telemetryModel.configMapName }}
            configMap:
              name: {{ .Values.telemetryModel.configMapName }}
              items:
              - key: model_configuration.yaml
                path: model_configuration.yaml
          restartPolicy: OnFailure
  schedule: "*/20 * * * *"