apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
data:
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "otel-collector"
        static_configs:
          - targets: ["otel-collector-prom-svc:9088"]

    remote_write:
      - url: "http://promscale-svc:9201/write"
    remote_read:
      - url: "http://promscale-svc:9201/read"
        read_recent: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        volumeMounts:
        - name: prometheus-conf
          mountPath: /etc/prometheus
        ports:
          - containerPort: 9090
      volumes:
      - name: prometheus-conf
        configMap:
          name: prometheus-conf
          items:
          - key: prometheus.yml
            path: prometheus.yml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-svc
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    app: prometheus
  type: ClusterIP