apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    name: otel-collector-conf
data:
  otelconfig.yaml: |-
    receivers:
      otlp:
        protocols:
          http:

    processors:
      batch:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9088"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib
        name: otel-collector
        volumeMounts:
        - name: otel-collector-conf
          mountPath: /etc/otel
        ports:
          - containerPort: 55681
          - containerPort: 9088
      volumes:
      - name: otel-collector-conf
        configMap:
          name: otel-collector-conf
          items:
          - key: otelconfig.yaml
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-collector
  name: otel-collector-prom-svc
spec:
  ports:
  - port: 9088
    protocol: TCP
  selector:
    app: otel-collector
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-collector
  name: otel-collector-ingest-svc
spec:
  ports:
  - port: 55681
    protocol: TCP
    nodePort: 30681
  selector:
    app: otel-collector
  type: NodePort