apiVersion: v1
kind: Service
metadata:
  labels:
    app: timescaledb
  name: timescaledb-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: timescaledb
  type: ClusterIP