apiVersion: v1
data:
  {{ if .Values.timescaledb.password }}
  password:  {{ .Values.timescaledb.password | b64enc }}
  {{ else }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{ end }}
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.timescaledb.secretName }}