apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.timescaledb.deploymentName }}
  name: {{ .Values.timescaledb.deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.timescaledb.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.timescaledb.deploymentName }}
    spec:
      containers:
      - image: timescaledev/promscale-extension:latest-ts2-pg13
        name: promscale-extension
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.timescaledb.secretName }}
                key: password