apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.timescaledb.deploymentName }}
  name: {{ .Values.timescaledb.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: {{ .Values.timescaledb.deploymentName }}
  type: ClusterIP