apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.promscale.deploymentName }}
  name: {{ .Values.promscale.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9201
    protocol: TCP
  selector:
    app: {{ .Values.promscale.deploymentName }}
  type: ClusterIP