apiVersion: v1
kind: Service
metadata:
  labels:
    app: promscale
  name: promscale-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9201
    protocol: TCP
  selector:
    app: promscale
  type: ClusterIP