apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-lb
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000